name: Build Docker images

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: RobinJ1995
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Build and push multi-platform image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/robinj1995/totaleblindheidbot/totale-blindheid-bot:latest
            ghcr.io/robinj1995/totaleblindheidbot/totale-blindheid-bot:${{ github.sha }}

      - name: Trigger deployment
        if: ${{ success() }}
        run: |
          curl -sS --fail -X PUT -H "Authorization: Bearer ${{ secrets.KUBECONTROL_TOKEN }}" https://kuber1.robinj.be/deployment/telegram-bots/totale-blindheid
